[package]
authors = ["Walther Chen <walther.chen@gmail.com>"]
description = "Library to interface with Secret Service API"
documentation = "https://docs.rs/secret-service"
homepage = "https://github.com/hwchen/secret-service-rs.git"
keywords = ["secret-service", "password", "linux", "keychain"]
license-file = "LICENSE"
name = "secret-service"
repository = "https://github.com/hwchen/secret-service-rs.git"
edition = "2021"
version = "3.0.0"
rust-version = "1.60.0"

# The async runtime features mirror those of `zbus` for compatibility.
[features]
default = ["async-io", "rs-crypto"]
async-io = ["zbus/async-io"]
tokio = ["zbus/tokio"]
rs-crypto = ["dep:aes", "dep:block-modes", "dep:sha2", "dep:hkdf"]
vendored-openssl = ["openssl", "openssl/vendored"]

[dependencies]
openssl = { version = 0.10.40", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }aes = { version = "0.7.0", optional = true }
block-modes = { version = "0.8.0", optional = true }
hkdf = { version = "0.12.0", optional = true }
generic-array = "0.14"
once_cell = { version = "1" }
futures-util = "0.3"
num = { version = "0.4.0" }
rand = { version = "0.8.1" }
serde = { version = "1.0", features = ["derive"] }
sha2 = { version = "0.10.0", optional = true }
zbus = { version = "3", default-features = false }# TODO: Update these when Rust 1.56 isn't so new.
